# Generated by Django 4.1.5 on 2023-10-04 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="user_type",
            new_name="usertype",
        ),
    ]
